# Generated by Django 6.0.5 on 2026-05-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('year_of_establishment', models.IntegerField()),
                ('logo', models.ImageField(upload_to='academy_logos/')),
                ('trust_registration_number', models.CharField(max_length=255, unique=True)),
                ('office_address', models.TextField()),
                ('office_phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('no_of_players', models.IntegerField()),
                ('registration_certificate', models.ImageField(upload_to='registration_certificates/')),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('transaction_image', models.ImageField(upload_to='transaction_images/')),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
