# Generated by Django 6.0.5 on 2026-06-11 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_academy_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academy',
            name='adhyaksha',
        ),
        migrations.RemoveField(
            model_name='academy',
            name='koshadhyaksha',
        ),
        migrations.RemoveField(
            model_name='academy',
            name='sachiv',
        ),
        migrations.AddField(
            model_name='academy',
            name='coach_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='coach_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='academy',
            name='coach_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='coach_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='coach_upha_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academy_director', to=settings.AUTH_USER_MODEL),
        ),
    ]
