# Generated by Django 6.0.5 on 2026-06-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_remove_academy_adhyaksha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='registration_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='registration_certificates/'),
        ),
        migrations.AlterField(
            model_name='academy',
            name='trust_registration_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
