# Generated by Django 6.0.5 on 2026-06-12 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_alter_academy_registration_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='academy_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='address_proof',
            field=models.ImageField(blank=True, null=True, upload_to='address_proofs/'),
        ),
        migrations.AddField(
            model_name='academy',
            name='bank_details',
            field=models.ImageField(blank=True, null=True, upload_to='bank_details/'),
        ),
        migrations.AddField(
            model_name='academy',
            name='categories_trained',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='coach_grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='coaches_employed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='academy',
            name='discipline_focus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='training_venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='AcademyFacilityPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='academy_facilities/')),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_photos', to='academy.academy')),
            ],
        ),
    ]
