# Generated by Django 6.0.5 on 2026-06-11 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_date', models.DateField(blank=True, null=True)),
                ('total_matches', models.PositiveIntegerField(blank=True, null=True)),
                ('top_scorer', models.CharField(blank=True, default='', max_length=255)),
                ('best_player', models.CharField(blank=True, default='', max_length=255)),
                ('best_goalkeeper', models.CharField(blank=True, default='', max_length=255)),
                ('most_promising_junior', models.CharField(blank=True, default='', max_length=255)),
                ('scoresheet', models.FileField(blank=True, null=True, upload_to='scoresheets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('team_name', models.CharField(max_length=255)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='events.event')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
