# Generated by Django 4.2.23 on 2026-06-01 08:37

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('press_release', 'Press Release'), ('achievement', 'Achievement'), ('photo', 'Photo'), ('video', 'Video')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('media_file', models.FileField(upload_to=gallery.models.gallery_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
