# Generated by Django 6.0.5 on 2026-06-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryalbum_galleryphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryalbum',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
