# Generated by Django 6.0.5 on 2026-08-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_galleryalbum_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryalbum',
            name='youtube_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
