# Generated by Django
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('year_of_establishment', models.IntegerField()),
                ('logo', models.ImageField(upload_to='district_logos/')),
                ('trust_registration_number', models.CharField(max_length=255, unique=True)),
                ('office_address', models.TextField()),
                ('office_phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('no_of_players', models.IntegerField()),
                ('registration_certificate', models.ImageField(upload_to='registration_certificates/')),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('transaction_image', models.ImageField(upload_to='transaction_images/')),
                ('paid', models.BooleanField(default=False)),
                ('adhyaksha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_adhyaksha', to=settings.AUTH_USER_MODEL)),
                ('koshadhyaksha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_koshadhyaksha', to=settings.AUTH_USER_MODEL)),
                ('sachiv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_sachiv', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
