# Generated by Django 6.0.5 on 2026-06-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0002_district_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='registration_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='registration_certificates/'),
        ),
        migrations.AlterField(
            model_name='district',
            name='trust_registration_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
