# Generated by Django 6.0.5 on 2026-06-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoachAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('award_name', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=10)),
                ('role_description', models.CharField(max_length=255)),
                ('coach_id_str', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FederationAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('award_name', models.CharField(max_length=255)),
                ('awarded_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('player_id_str', models.CharField(blank=True, max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('event_location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category_tag', models.CharField(max_length=255)),
                ('color_theme', models.CharField(choices=[('blue', 'Blue'), ('orange', 'Orange'), ('green', 'Green'), ('dark', 'Dark')], default='blue', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
