# Generated by Django 6.0.5 on 2026-05-30 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='highest_qualification',
            new_name='highest_coaching_grade',
        ),
    ]
