# Generated by Django 6.0.5 on 2026-05-30 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_highest_qualification_coach_highest_coaching_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('coach', 'Coach'), ('player', 'Player'), ('referee', 'Referee')], default='player', max_length=20),
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=255)),
                ('occupation', models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('self_employed', 'Self Employed')], default='self_employed', max_length=255)),
                ('grade_applying_for', models.CharField(max_length=255)),
                ('year_of_officiating_experience', models.IntegerField()),
                ('highest_level_officiated', models.CharField(max_length=255)),
                ('tournament_officiated', models.TextField()),
                ('previous_referee_id', models.CharField(max_length=255, unique=True)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('transaction_image', models.ImageField(upload_to='transaction_images/')),
                ('paid', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
