# Generated by Django 6.0.5 on 2026-06-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role_referee'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_images/'),
        ),
    ]
