# Generated by Django 6.0.5 on 2026-06-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_decisionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('coach', 'Coach'), ('player', 'Player'), ('referee', 'Referee'), ('academy', 'Academy'), ('district', 'District')], default='player', max_length=20),
        ),
    ]
