# Generated by Django 6.0.5 on 2026-06-10 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_decisionlog_admin_alter_decisionlog_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeBearer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='office_bearers/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='decisionlog',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='decisionlog',
            name='details',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
