# Generated by Django 6.0.5 on 2026-06-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_announcement_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_qr_code', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('player_fee', models.IntegerField(default=111)),
                ('referee_fee', models.IntegerField(default=300)),
                ('coach_fee', models.IntegerField(default=300)),
                ('academy_fee', models.IntegerField(default=2500)),
                ('district_fee', models.IntegerField(default=1100)),
            ],
        ),
    ]
