# Generated by Django 6.0.5 on 2026-06-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='facebook_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='instagram_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='twitter_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='youtube_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='academy_fee',
            field=models.IntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='district_fee',
            field=models.IntegerField(default=5100),
        ),
    ]
