# Generated by Django 6.0.5 on 2026-06-14 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_systemsettings_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='valid_through',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RenewalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('transaction_image', models.ImageField(upload_to='renewal_images/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
