# Generated by Django 6.0.5 on 2026-08-08 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_valid_through_renewalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGMLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('letter_date', models.DateField()),
                ('letter_type', models.CharField(choices=[('text', 'Text Letter'), ('pdf', 'PDF Document')], default='text', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='agm_letters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agm_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-letter_date', '-created_at'),
            },
        ),
    ]
