# Generated by Django 6.0.5 on 2026-08-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_agm_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPHAForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='upha_forms/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='hai_affiliation_letter',
            field=models.FileField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='up_olympic_letter',
            field=models.FileField(blank=True, null=True, upload_to='settings/'),
        ),
    ]
