# Generated by Django 6.0.5 on 2026-08-10 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_uphaform_systemsettings_hai_affiliation_letter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='hai_affiliation_letter',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='up_olympic_letter',
        ),
    ]
