# Generated by Django 6.0.5 on 2026-08-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_systemsettings_hai_affiliation_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='hai_affiliation_letter',
            field=models.FileField(blank=True, null=True, upload_to='settings/affiliation/'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='up_olympic_letter',
            field=models.FileField(blank=True, null=True, upload_to='settings/affiliation/'),
        ),
    ]
