# Generated by Django 6.0.5 on 2026-08-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_systemsettings_hai_affiliation_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='upha2024@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='contact_mobile',
            field=models.CharField(blank=True, default='+91 75700 99990', max_length=255),
        ),
    ]
