# Generated by Django 6.0.5 on 2026-08-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_systemsettings_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='contact_address',
            field=models.TextField(blank=True, default='K.D. Singh Babu Stadium, Lucknow\n(Branch: Chandpur, Varanasi)'),
        ),
    ]
