# Generated by Django 6.0.5 on 2026-09-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_systemsettings_contact_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='officebearer',
            name='term',
            field=models.CharField(blank=True, default='2023 - 2027', max_length=50),
        ),
    ]
